# Generated by Django 4.0.5 on 2022-06-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('user_type', models.CharField(choices=[('S', 'Staff'), ('P', 'Parents'), ('KS', 'Kindergarten Student'), ('ES', 'Elementary Student'), ('HS', 'Highschool Student')], max_length=2, verbose_name='student type')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
