# Generated by Django 4.0.5 on 2022-06-18 05:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
                ('push_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, verbose_name='department')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
                ('push_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
