# Generated by Django 4.0.5 on 2022-07-20 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('emoji', models.CharField(max_length=20, verbose_name='title emoji')),
                ('content', models.TextField(max_length=83, verbose_name='content')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('activity_date', models.DateTimeField(verbose_name='date of activity')),
                ('thumbnail_URL', models.URLField(verbose_name='thumbnail url')),
                ('video_URL', models.URLField(blank=True, null=True, verbose_name='video url')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('emoji', models.CharField(max_length=20, verbose_name='title emoji')),
                ('content', models.TextField(max_length=150, verbose_name='content')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('department', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, null=True, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(verbose_name='score')),
                ('team_color', models.CharField(choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, verbose_name='team color')),
                ('department', models.CharField(choices=[('E', 'Elementary'), ('H', 'Highschool')], max_length=2, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, verbose_name='department')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_id', models.CharField(max_length=100, verbose_name='exponent push id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
