# Generated by Django 4.0.5 on 2022-07-25 13:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('emoji', models.CharField(max_length=20, verbose_name='title emoji')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('activity_date', models.DateTimeField(verbose_name='date of activity')),
                ('thumbnail_URL', models.URLField(blank=True, null=True, verbose_name='thumbnail url')),
                ('thumbnail_File', models.FileField(blank=True, null=True, upload_to='', verbose_name='thumbnail file')),
                ('video_URL', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('notification', models.BooleanField(verbose_name='Send Notification to User')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('T', 'Teacher/Staff')], max_length=1, verbose_name='user type')),
                ('department', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, null=True, verbose_name='department')),
                ('team_color', models.CharField(blank=True, choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, null=True, verbose_name='team color')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('emoji', models.CharField(max_length=20, verbose_name='title emoji')),
                ('redirect_URI', models.URLField(verbose_name='redirect URI')),
                ('bg_color1', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('bg_color2', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('emoji', models.CharField(max_length=20, verbose_name='title emoji')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('department', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, null=True, verbose_name='department')),
                ('notification', models.BooleanField(verbose_name='Send Notification to User')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('content', models.TextField(max_length=200, verbose_name='conent')),
                ('date_updated', models.DateTimeField(verbose_name='thumbnail_url')),
                ('image_URL', models.FileField(upload_to='', verbose_name='photo')),
                ('notification', models.BooleanField(verbose_name='Send Notification to User')),
            ],
        ),
        migrations.CreateModel(
            name='PushID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_id', models.CharField(max_length=100, verbose_name='exponent push id')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(verbose_name='score')),
                ('team_color', models.CharField(choices=[('R', 'Red Team'), ('G', 'Green Team'), ('B', 'Blue Team'), ('Y', 'Yellow Team')], max_length=1, verbose_name='team color')),
                ('department', models.CharField(choices=[('E', 'Elementary'), ('H', 'Highschool')], max_length=2, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='GPAScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='cumulative gpa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appuser')),
            ],
        ),
    ]
