# Generated by Django 4.0.5 on 2022-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pushid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='thumbnail_File',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='thumbnail file'),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(default='John Doe', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='John Doe', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='John Doe', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumbnail_URL',
            field=models.URLField(blank=True, null=True, verbose_name='thumbnail url'),
        ),
    ]
