# Generated by Django 4.0.5 on 2022-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='title')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('department', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('E', 'Elementary'), ('H', 'Highschool')], max_length=2, null=True, verbose_name='department')),
            ],
        ),
    ]
