# Generated by Django 4.0.5 on 2022-07-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_post_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title_emoji',
            new_name='emoji',
        ),
    ]
