# Generated by Django 4.0.5 on 2022-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(max_length=300, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=300, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.TextField(max_length=200, verbose_name='conent'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
    ]
