# Generated by Django 4.0.5 on 2022-07-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_gpascore_delete_parent_delete_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Send Notification to User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Send Notification to User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Send Notification to User'),
            preserve_default=False,
        ),
    ]
