# Generated by Django 4.0.5 on 2022-07-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_notification_news_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpascore',
            name='gpa',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='cumulative gpa'),
        ),
    ]
